repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
      - id: check-case-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer

  - repo: https://github.com/timothycrosley/isort
    rev: 5.2.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.9.0
    hooks:
      - id: markdownlint

default_language_version:
  python: python3.8

fail_fast: true
